#!/usr/bin/env bash
# setup-firebase.sh — Generate Firebase config files from env vars.
#
# Replaces the manual `flutterfire configure` step. Reads Firebase credentials
# from local-dev/.env and writes:
#   - mobile/lib/firebase_options.dart
#   - mobile/ios/Runner/GoogleService-Info.plist
#   - mobile/android/app/google-services.json
#
# Usage:
#   ./local-dev/setup-firebase.sh
#
# Required vars in local-dev/.env:
#   FIREBASE_PROJECT_ID          e.g. move-with-fergie
#   FIREBASE_IOS_API_KEY         from Firebase console → Project settings → iOS app
#   FIREBASE_IOS_APP_ID          e.g. 1:826982026670:ios:xxxxxxxxxxxx
#   FIREBASE_IOS_MESSAGING_ID    e.g. 826982026670
#   FIREBASE_IOS_STORAGE_BUCKET  e.g. move-with-fergie.appspot.com
#   FIREBASE_ANDROID_API_KEY     from Firebase console → Project settings → Android app
#   FIREBASE_ANDROID_APP_ID      e.g. 1:826982026670:android:xxxxxxxxxxxx

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[[ -f "$REPO_ROOT/local-dev/.env" ]] && source "$REPO_ROOT/local-dev/.env"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
step() { echo -e "\n${GREEN}${BOLD}▶ $*${NC}"; }
info() { echo -e "${CYAN}   $*${NC}"; }
warn() { echo -e "${YELLOW}⚠  $*${NC}"; }
die()  { echo -e "${RED}✗  $*${NC}"; exit 1; }

# ── validate required vars ────────────────────────────────────────────────────
REQUIRED_VARS=(
  FIREBASE_PROJECT_ID
  FIREBASE_IOS_API_KEY
  FIREBASE_IOS_APP_ID
  FIREBASE_IOS_MESSAGING_ID
  FIREBASE_IOS_STORAGE_BUCKET
  FIREBASE_ANDROID_API_KEY
  FIREBASE_ANDROID_APP_ID
)

MISSING=()
for var in "${REQUIRED_VARS[@]}"; do
  [[ -z "${!var:-}" ]] && MISSING+=("$var")
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo ""
  echo -e "${RED}${BOLD}✗  Missing Firebase credentials in local-dev/.env:${NC}"
  for v in "${MISSING[@]}"; do
    echo "     $v"
  done
  echo ""
  echo "  How to get these values:"
  echo "  1. Go to https://console.firebase.google.com → your project"
  echo "  2. Project settings → General → Your apps"
  echo "  3. iOS app → GoogleService-Info.plist → open and copy values"
  echo "  4. Android app → google-services.json → open and copy values"
  echo ""
  echo "  Paste them into local-dev/.env and re-run this script."
  exit 1
fi

BUNDLE_ID="com.fererelabs.mwfMobile"
ANDROID_PKG="com.fererelabs.mwf_mobile"

# ── 1. firebase_options.dart ──────────────────────────────────────────────────
step "Writing mobile/lib/firebase_options.dart"

cat > "$REPO_ROOT/mobile/lib/firebase_options.dart" << DART
// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by local-dev/setup-firebase.sh from local-dev/.env
// Do not commit real credentials. firebase_options.dart is gitignored.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '${FIREBASE_ANDROID_API_KEY}',
    appId: '${FIREBASE_ANDROID_APP_ID}',
    messagingSenderId: '${FIREBASE_IOS_MESSAGING_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_IOS_STORAGE_BUCKET}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '${FIREBASE_IOS_API_KEY}',
    appId: '${FIREBASE_IOS_APP_ID}',
    messagingSenderId: '${FIREBASE_IOS_MESSAGING_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_IOS_STORAGE_BUCKET}',
    iosBundleId: '${BUNDLE_ID}',
  );
}
DART

info "firebase_options.dart written"

# ── 2. GoogleService-Info.plist ───────────────────────────────────────────────
step "Writing mobile/ios/Runner/GoogleService-Info.plist"

cat > "$REPO_ROOT/mobile/ios/Runner/GoogleService-Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>API_KEY</key>
	<string>${FIREBASE_IOS_API_KEY}</string>
	<key>GCM_SENDER_ID</key>
	<string>${FIREBASE_IOS_MESSAGING_ID}</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>${BUNDLE_ID}</string>
	<key>PROJECT_ID</key>
	<string>${FIREBASE_PROJECT_ID}</string>
	<key>STORAGE_BUCKET</key>
	<string>${FIREBASE_IOS_STORAGE_BUCKET}</string>
	<key>IS_ADS_ENABLED</key>
	<false/>
	<key>IS_ANALYTICS_ENABLED</key>
	<false/>
	<key>IS_APPINVITE_ENABLED</key>
	<true/>
	<key>IS_GCM_ENABLED</key>
	<true/>
	<key>IS_SIGNIN_ENABLED</key>
	<true/>
	<key>GOOGLE_APP_ID</key>
	<string>${FIREBASE_IOS_APP_ID}</string>
</dict>
</plist>
PLIST

info "GoogleService-Info.plist written"

# ── 3. google-services.json ───────────────────────────────────────────────────
step "Writing mobile/android/app/google-services.json"

# Derive project number from messaging sender ID (they are the same)
PROJECT_NUMBER="${FIREBASE_IOS_MESSAGING_ID}"

cat > "$REPO_ROOT/mobile/android/app/google-services.json" << JSON
{
  "project_info": {
    "project_number": "${PROJECT_NUMBER}",
    "project_id": "${FIREBASE_PROJECT_ID}",
    "storage_bucket": "${FIREBASE_IOS_STORAGE_BUCKET}"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "${FIREBASE_ANDROID_APP_ID}",
        "android_client_info": {
          "package_name": "${ANDROID_PKG}"
        }
      },
      "api_key": [
        {
          "current_key": "${FIREBASE_ANDROID_API_KEY}"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": []
        }
      }
    }
  ],
  "configuration_version": "1"
}
JSON

info "google-services.json written"

# ── 4. verify .gitignore entries ──────────────────────────────────────────────
step "Checking .gitignore"

GITIGNORE="$REPO_ROOT/.gitignore"
MISSING_IGNORES=()

for entry in \
  "mobile/lib/firebase_options.dart" \
  "mobile/ios/Runner/GoogleService-Info.plist" \
  "mobile/android/app/google-services.json"; do
  grep -qF "$entry" "$GITIGNORE" 2>/dev/null || MISSING_IGNORES+=("$entry")
done

if [[ ${#MISSING_IGNORES[@]} -gt 0 ]]; then
  warn "Adding missing .gitignore entries:"
  for entry in "${MISSING_IGNORES[@]}"; do
    echo "  $entry" >> "$GITIGNORE"
    info "Added: $entry"
  done
fi

# ── done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}✓ Firebase config generated from local-dev/.env${NC}"
echo ""
info "Files written:"
info "  mobile/lib/firebase_options.dart"
info "  mobile/ios/Runner/GoogleService-Info.plist"
info "  mobile/android/app/google-services.json"
echo ""
info "These files are gitignored — never committed."
info "Run this script on every new machine / checkout."
echo ""
